### ISSUE TITLE
.NET Core 3.0 support?

### ISSUE THREAD

**Issue by ymassad** [michaellperry/UpdateControls#17]
Are there plans to make this library support .NET Core 3.0?

**Comment by michaellperry** [comment]
Thank you for your interest. I have moved my attention over to [Assisticant](https://github.com/michaellperry/Assisticant), which is a modernized version of Update Controls. Assisticant focuses on XAML, and leaves Windows Forms support behind.

I have had one failed attempt to port Assisticant to .NET Core, but plan to try again with 3.0.

**Comment by ymassad** [comment]
Thanks.
